---

- name: Config tasks
  when: systemd_timesyncd_package_ensure == 'present'
  tags:
    - systemd_timesyncd_config
    - systemd_timesyncd
  become: true
  block:
    - name: Manage global configuration
      when: systemd_timesyncd_config_options is defined and systemd_timesyncd_config_options
      ansible.builtin.template:
        src: timesyncd.conf.j2
        dest: "{{ systemd_timesyncd_config_file }}"
        mode: "0644"
        owner: root
        group: root
      notify: Restart systemd-timesyncd
