---

- name: Config tasks
  when: systemd_timesyncd_package_ensure == 'present'
  tags:
    - systemd_timesyncd_config
    - systemd_timesyncd
  become: true
  block:
    - name: Make dropin config directory
      when: systemd_timesyncd_dropin_config_options is defined and systemd_timesyncd_dropin_config_options
      ansible.builtin.file:
        path: "{{ systemd_timesyncd_dropin_config_dir }}"
        mode: "0755"
        owner: root
        group: root
        state: directory

    - name: Initialize dropin config
      when: systemd_timesyncd_dropin_config_options is defined and systemd_timesyncd_dropin_config_options
      block:

        - name: Search dropin config
          ansible.builtin.find:
            paths: "{{ systemd_timesyncd_dropin_config_dir }}"
            patterns: "*.conf"
          register: findlist

        - name: Current dropin config
          ansible.builtin.set_fact:
            systemd_timesyncd_dropin_before: "{{ findlist['files'] | map(attribute='path') | flatten }}"

        - name: Generate dropin config
          ansible.builtin.set_fact:
            systemd_timesyncd_dropin_temp: "{{ systemd_timesyncd_dropin_config_options | map(attribute='name') | flatten }}"

        - name: Generate dropin config
          ansible.builtin.set_fact:
            systemd_timesyncd_dropin_after: "{{ systemd_timesyncd_dropin_after | default([]) }} + [ {{ systemd_timesyncd_dropin_config_dir }}/{{ item }} ] | flatten }}"
          with_items: "{{ systemd_timesyncd_dropin_temp }}"

        - name: Remove target dropin config
          ansible.builtin.set_fact:
            systemd_timesyncd_dropin_remove: "{{ systemd_timesyncd_dropin_before | difference(systemd_timesyncd_dropin_after) }}"

        - name: Debug variable print 
          when: systemd_timesyncd_debug is defined and systemd_timesyncd_debug
          ansible.builtin.import_tasks: debug/dropin.yml

        - name: Remove dropin config
          when: systemd_timesyncd_dropin_remove is defined
          ansible.builtin.file:
            path: "{{ item }}"
            state: absent
          with_items: "{{ systemd_timesyncd_dropin_remove }}"
          notify: Restart systemd-timesyncd

    - name: Manage dropin configuration
      when: systemd_timesyncd_dropin_config_options is defined and systemd_timesyncd_dropin_config_options
      ansible.builtin.template:
        src: timesyncd.dropin.j2
        dest: "{{ systemd_timesyncd_dropin_config_dir }}/{{ item.name }}"
        mode: "0644"
        owner: root
        group: root
      notify: Restart systemd-timesyncd
      with_items: "{{ systemd_timesyncd_dropin_config_options }}"